### ISSUE TITLE
Error to add SPN to analysis services role member

### ISSUE THREAD

**Issue by deshnpra** [tdjastrzebski/azure-enterprise-reports#2]
Hi,

Looking on to your solution it seems its a great solution to capture billing details in various formats. For one of our requirement we are following this solution and we have successfully implemented till step number 14. we are currently stuck at step number 15 where we are trying to edit admin under roles in AnalysisServiceDatabase. The moment we are trying to edit Admin and selecting the find user then we are getting the following error. Could you please suggest something on this what we are not following correctly. It would be of great help.
Few things which we have already taken care are:
1) SPN has been created in AAD tenant 
2) My user is part of AAD tenant of the same subscription as member

 
Error to add SPN to analysis services role member

```
Error` Message:
============================Failed to save modifications to the server. Error returned: 'ID cannot be specified for Azure Analysis Services role member: '<pii>app:9a6503fd-5c1e-4970-b575-72832966b5be@cbede638-a3d9-459f-8f4e-24ced73b4e5e</pii>'.Technical Details:
RootActivityId: e77d980f-1459-4246-b77a-a8f6e20e350b
Date (UTC): 10/1/2020 11:22:39 AM
'.
----------------------------
Failed to save modifications to the server. Error returned: 'ID cannot be specified for Azure Analysis Services role member: '<pii>app:9a6503fd-5c1e-4970-b575-72832966b5be@cbede638-a3d9-459f-8f4e-24ced73b4e5e</pii>'.Technical Details:
RootActivityId: e77d980f-1459-4246-b77a-a8f6e20e350b
Date (UTC): 10/1/2020 11:22:39 AM
'.============================
Call Stack:
============================ at Microsoft.AnalysisServices.BackEnd.DataModelingSandboxTabular.ExecuteEngineCodeInBackground(OperationType type, Boolean cancellable, AMOCode code, Boolean raiseEvents)
at Microsoft.AnalysisServices.BackEnd.DataModelingSandboxTabular.DoExecuteEngineCode(OperationType type, OperationCancellability cancellable, AMOCode code, Boolean raiseEvents)
at Microsoft.AnalysisServices.BackEnd.DataModelingSandbox.ExecuteEngineCode(OperationType type, OperationCancellability cancellable, AMOCode code, Boolean raiseEvents)
at Microsoft.AnalysisServices.BackEnd.DataModelingRoleTabular.Update(DataModelingSandbox sandbox, String name, String description, IEnumerable`1 roleMembers, DataModelingRolePermission permission, Dictionary`2 tableDaxPairs, Dictionary`2 rolePermissionChanges)
----------------------------
at Microsoft.AnalysisServices.BackEnd.DataModelingRoleTabular.Update(DataModelingSandbox sandbox, String name, String description, IEnumerable`1 roleMembers, DataModelingRolePermission permission, Dictionary`2 tableDaxPairs, Dictionary`2 rolePermissionChanges)
at Microsoft.AnalysisServices.Common.RoleManagerDlg.SaveChanges()============================


```

**Comment by tdjastrzebski** [comment]
@deshnpra I think it is a known Microsoft bug. I have experienced a similar issue https://developercommunity.visualstudio.com/content/problem/264006/ssas-tabular-adding-service-principal-to-role-caus.html  
See Microsoft's response.

Do you modify permissions using Visial Studio 2019 with "Microsoft Analysis Services Projects" or Microsoft SQL Server Management Studio?

**Comment by deshnpra** [comment]
Yes, We are using the visual studio enterprise edition to modify the permission.

 Could you please suggest, if is it any another way or workaround to achieve it

**Comment by tdjastrzebski** [comment]
I think you should be able modify these permissions using Microsoft SQL Server Management Studio as well.

Are you using the latest VS Studio? Which version of "Microsoft Analysis Services Projects" extension are you using?
